name: Deploy Quadrinopolis Web to GitHub Pages

on:
  push:
    branches:
      - main  # ou "master", depende de qual branch você usa

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Quadrinopolis-web   # pasta onde está o index.html

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
